"""remove rank column

Revision ID: 25933b8dc6dc
Revises: fa54abde731f
Create Date: 2025-07-04 21:15:33.986812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25933b8dc6dc'
down_revision: Union[str, None] = 'fa54abde731f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_win_rate', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_win_rate', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
