"""gwent base model

Revision ID: ee6d372c26ea
Revises: f0ce06ad78f4
Create Date: 2025-06-12 07:56:42.924619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6d372c26ea'
down_revision: Union[str, None] = 'f0ce06ad78f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overall_win_rate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nilfgaard_wr', sa.Double(), nullable=False),
    sa.Column('monsters_wr', sa.Double(), nullable=False),
    sa.Column('skellige_wr', sa.Double(), nullable=False),
    sa.Column('northern_realms_wr', sa.Double(), nullable=False),
    sa.Column('syndicate_wr', sa.Double(), nullable=False),
    sa.Column('scoiatael_wr', sa.Double(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gwent_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gwent_id')
    )
    op.create_table('rank_win_rate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('nilfgaard_wr', sa.Double(), nullable=False),
    sa.Column('monsters_wr', sa.Double(), nullable=False),
    sa.Column('skellige_wr', sa.Double(), nullable=False),
    sa.Column('northern_realms_wr', sa.Double(), nullable=False),
    sa.Column('syndicate_wr', sa.Double(), nullable=False),
    sa.Column('scoiatael_wr', sa.Double(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_win_rate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nilfgaard_wr', sa.Double(), nullable=False),
    sa.Column('monsters_wr', sa.Double(), nullable=False),
    sa.Column('skellige_wr', sa.Double(), nullable=False),
    sa.Column('northern_realms_wr', sa.Double(), nullable=False),
    sa.Column('syndicate_wr', sa.Double(), nullable=False),
    sa.Column('scoiatael_wr', sa.Double(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_win_rate')
    op.drop_table('rank_win_rate')
    op.drop_table('players')
    op.drop_table('overall_win_rate')
    # ### end Alembic commands ###
