"""Players count for winrate models

Revision ID: fa54abde731f
Revises: 37c60fa8b42a
Create Date: 2025-06-24 09:11:50.650534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa54abde731f'
down_revision: Union[str, None] = '37c60fa8b42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overall_win_rate', sa.Column('players_count', sa.Integer(), nullable=True))
    op.add_column('rank_win_rate', sa.Column('players_count', sa.Integer(), nullable=True))
    op.add_column('top_win_rate', sa.Column('players_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_win_rate', 'players_count')
    op.drop_column('rank_win_rate', 'players_count')
    op.drop_column('overall_win_rate', 'players_count')
    # ### end Alembic commands ###
